# site title
title: Gaodb

# user name or organization name
user: gxyz

# issue repository
repository: gxyz.github.io

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 0ac488042eccb5a169fcc74feef307aa7862713f

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
